### ISSUE TITLE
Empty screen when there are no groups

### ISSUE THREAD

**Issue by mohitsoni-dev** [nishant-boro/split-it-easy-android#2]
Dear developer,
I have found a scope of UI enhancement. That is when there are 0 groups, the group activity displays an empty screen. It should display a text that there are no groups and please create a new group.
I would like to solve this issue and will be grateful to contribute.
![ss](https://user-images.githubusercontent.com/59525097/103865251-ec7ab980-50e9-11eb-88f4-268205977468.jpeg)

**Comment by nishant-boro** [comment]
Sure. You can work on it and then send a request to merge it. If you need any help or have any other queries, you can contact me.

**Comment by mohitsoni-dev** [comment]
> Sure. You can work on it and then send a request to merge it. If you need any help or have any other queries, you can contact me.
I solved this issue and made a PR. Please review it. Thanks.

**Comment by ghost** [comment]
PR Merged.
